/** Centralized error messages — no hardcoding allowed in controllers/services */
export const ERROR_MESSAGES = {
  // Auth
  USER_NOT_FOUND: 'User not found.',
  INVALID_CREDENTIALS: 'Invalid email or password.',
  EMAIL_ALREADY_EXISTS: 'User with this email already exists.',
  UNAUTHORIZED: 'Unauthorized access.',
  FORBIDDEN: 'You do not have permission to perform this action.',
  ACCOUNT_SUSPENDED: 'This account has been suspended. Please contact support.',

  // Patients
  PATIENT_NOT_FOUND: 'Patient profile not found.',
  ONBOARDING_INCOMPLETE:
    'Please complete onboarding before accessing this feature.',

  // Family / Care Circle
  CONNECTION_NOT_FOUND: 'Care circle connection not found.',
  CONNECTION_ALREADY_INVITED:
    'This person has already been invited to your care circle.',

  // Discovery / Waitlist
  FAVORITE_ALREADY_EXISTS: 'This doctor is already in your favourites.',
  FAVORITE_NOT_FOUND: 'Favourite not found.',
  WAITLIST_ENTRY_NOT_FOUND: 'Waitlist entry not found.',

  // Doctors
  DOCTOR_NOT_FOUND: 'Doctor not found or not verified.',
  KYC_ALREADY_SUBMITTED: 'KYC documents have already been submitted.',
  DOCTOR_NOT_VERIFIED:
    'Your account is pending admin verification. You will get access to patient data once approved.',
  DOCTOR_ON_LEAVE: 'The doctor is on leave on the requested date.',

  // Appointments
  APPOINTMENT_NOT_FOUND: 'Appointment not found.',
  APPOINTMENT_CONFLICT: 'The selected time slot is already booked.',
  APPOINTMENT_PAST_DATE: 'Cannot book an appointment in the past.',
  APPOINTMENT_ALREADY_CANCELLED: 'This appointment is already cancelled.',
  APPOINTMENT_ALREADY_COMPLETED: 'This appointment cannot be modified because it has already been completed.',
  INVALID_APPOINTMENT_STATUS: 'Invalid appointment status transition.',

  // Records
  PRESCRIPTION_NOT_FOUND: 'Prescription not found.',
  PRESCRIPTION_ALREADY_SIGNED: 'This prescription has already been signed and cannot be modified.',
  LAB_RESULT_NOT_FOUND: 'Lab result not found.',
  REFILL_NOT_FOUND: 'Refill request not found.',
  LAB_REPORT_REQUEST_NOT_FOUND: 'Lab report request not found.',
  LAB_REPORT_ALREADY_REVIEWED:
    'This report has already been reviewed and can no longer be removed.',
  INVALID_FILE_TYPE: 'Unsupported file type. Please upload a PDF, JPG, or PNG.',
  INVALID_IMAGE_TYPE:
    'Unsupported file type. Please upload a JPG, PNG, or WebP image.',
  FILE_TOO_LARGE: 'File is too large. Maximum size is 15MB.',
  FILE_REQUIRED: 'Please attach a file.',

  // Admin
  VERIFICATION_NOT_FOUND: 'Verification request not found.',
  REFUND_NOT_FOUND: 'Refund request not found.',
  TICKET_NOT_FOUND: 'Support ticket not found.',
  SPECIALTY_NOT_FOUND: 'Specialty not found.',
  SPECIALTY_ALREADY_EXISTS: 'A specialty with this name already exists.',

  // Records vault
  DOCUMENT_NOT_FOUND: 'Document not found.',
  CONTACT_NOT_FOUND: 'Emergency contact not found.',

  // Billing
  PAYMENT_NOT_FOUND: 'Payment not found.',
  PAYMENT_ALREADY_COMPLETED: 'Payment has already been completed for this appointment.',
  PAYMENT_SERVICE_UNAVAILABLE: 'Payment service is temporarily unavailable. Please try again later.',
  NOTHING_TO_CHARGE: 'There is nothing to charge for this appointment.',
  INSUFFICIENT_BALANCE: 'That amount is more than your available balance.',
  PAYOUT_FAILED: 'Unable to process payout request right now. Please try again later.',
  INVALID_COUPON_CODE: 'Invalid or expired coupon code.',

  // AI & Monetization
  AI_CREDITS_INSUFFICIENT: 'Insufficient AI credits. Please top up or upgrade your plan.',
  AI_PROVIDER_UNAVAILABLE: 'AI health assistant is temporarily unavailable. Please try again shortly.',

  // Staff
  STAFF_NOT_FOUND: 'Staff member not found.',
  LEAVE_NOT_FOUND: 'Leave request not found.',

  // Notifications
  NOTIFICATION_NOT_FOUND: 'Notification not found.',

  // Generic
  VALIDATION_ERROR: 'Validation failed',
  BAD_REQUEST: 'Bad request. Please check your parameters.',
  INTERNAL_SERVER_ERROR: 'Internal server error occurred. Please try again later.',
  SERVICE_UNAVAILABLE: 'Service is temporarily unavailable. Please try again later.',
};

/** Stable application-level machine-readable error codes */
export const ERROR_CODES = {
  // Auth & Identity
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  RESOURCE_ACCESS_DENIED: 'RESOURCE_ACCESS_DENIED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  CONFLICT_DUPLICATE_EMAIL: 'CONFLICT_DUPLICATE_EMAIL',

  // Validation
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',

  // Patients
  PATIENT_NOT_FOUND: 'PATIENT_NOT_FOUND',
  ONBOARDING_INCOMPLETE: 'ONBOARDING_INCOMPLETE',

  // Doctors
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  DOCTOR_NOT_VERIFIED: 'DOCTOR_NOT_VERIFIED',
  DOCTOR_UNAVAILABLE: 'DOCTOR_UNAVAILABLE',
  DOCTOR_ON_LEAVE: 'DOCTOR_ON_LEAVE',
  KYC_ALREADY_SUBMITTED: 'KYC_ALREADY_SUBMITTED',

  // Appointments
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND',
  APPOINTMENT_SLOT_UNAVAILABLE: 'APPOINTMENT_SLOT_UNAVAILABLE',
  APPOINTMENT_ALREADY_BOOKED: 'APPOINTMENT_ALREADY_BOOKED',
  APPOINTMENT_PAST_DATE: 'APPOINTMENT_PAST_DATE',
  APPOINTMENT_ALREADY_CANCELLED: 'APPOINTMENT_ALREADY_CANCELLED',
  APPOINTMENT_ALREADY_COMPLETED: 'APPOINTMENT_ALREADY_COMPLETED',
  INVALID_APPOINTMENT_STATUS: 'INVALID_APPOINTMENT_STATUS',

  // Records & Prescriptions
  PRESCRIPTION_NOT_FOUND: 'PRESCRIPTION_NOT_FOUND',
  PRESCRIPTION_ALREADY_SIGNED: 'PRESCRIPTION_ALREADY_SIGNED',
  LAB_REPORT_NOT_FOUND: 'LAB_REPORT_NOT_FOUND',
  LAB_REPORT_REQUEST_NOT_FOUND: 'LAB_REPORT_REQUEST_NOT_FOUND',
  LAB_REPORT_ALREADY_REVIEWED: 'LAB_REPORT_ALREADY_REVIEWED',
  DOCUMENT_NOT_FOUND: 'DOCUMENT_NOT_FOUND',
  FILE_TYPE_NOT_SUPPORTED: 'FILE_TYPE_NOT_SUPPORTED',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_REQUIRED: 'FILE_REQUIRED',

  // Billing & Payments
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_ALREADY_COMPLETED: 'PAYMENT_ALREADY_COMPLETED',
  PAYMENT_AMOUNT_MISMATCH: 'PAYMENT_AMOUNT_MISMATCH',
  PAYMENT_GATEWAY_UNAVAILABLE: 'PAYMENT_GATEWAY_UNAVAILABLE',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  PAYOUT_PROCESSING_FAILED: 'PAYOUT_PROCESSING_FAILED',
  INVALID_COUPON_CODE: 'INVALID_COUPON_CODE',

  // AI & Monetization
  AI_CREDITS_INSUFFICIENT: 'AI_CREDITS_INSUFFICIENT',
  AI_FEATURE_NOT_AVAILABLE: 'AI_FEATURE_NOT_AVAILABLE',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  SUBSCRIPTION_NOT_FOUND: 'SUBSCRIPTION_NOT_FOUND',
  PLAN_NOT_AVAILABLE: 'PLAN_NOT_AVAILABLE',

  // Admin & Catalog
  SPECIALTY_NOT_FOUND: 'SPECIALTY_NOT_FOUND',
  SPECIALTY_ALREADY_EXISTS: 'SPECIALTY_ALREADY_EXISTS',
  REFUND_NOT_FOUND: 'REFUND_NOT_FOUND',
  TICKET_NOT_FOUND: 'TICKET_NOT_FOUND',

  // General & System
  CONFLICT: 'CONFLICT',
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

/** Maps standard human-readable messages directly to their canonical error codes */
export const MESSAGE_TO_ERROR_CODE_MAP: Record<string, string> = {
  [ERROR_MESSAGES.USER_NOT_FOUND]: ERROR_CODES.USER_NOT_FOUND,
  [ERROR_MESSAGES.INVALID_CREDENTIALS]: ERROR_CODES.INVALID_CREDENTIALS,
  [ERROR_MESSAGES.EMAIL_ALREADY_EXISTS]: ERROR_CODES.CONFLICT_DUPLICATE_EMAIL,
  [ERROR_MESSAGES.UNAUTHORIZED]: ERROR_CODES.UNAUTHORIZED,
  [ERROR_MESSAGES.FORBIDDEN]: ERROR_CODES.FORBIDDEN,
  [ERROR_MESSAGES.ACCOUNT_SUSPENDED]: ERROR_CODES.ACCOUNT_SUSPENDED,
  [ERROR_MESSAGES.PATIENT_NOT_FOUND]: ERROR_CODES.PATIENT_NOT_FOUND,
  [ERROR_MESSAGES.ONBOARDING_INCOMPLETE]: ERROR_CODES.ONBOARDING_INCOMPLETE,
  [ERROR_MESSAGES.DOCTOR_NOT_FOUND]: ERROR_CODES.DOCTOR_NOT_FOUND,
  [ERROR_MESSAGES.DOCTOR_NOT_VERIFIED]: ERROR_CODES.DOCTOR_NOT_VERIFIED,
  [ERROR_MESSAGES.DOCTOR_ON_LEAVE]: ERROR_CODES.DOCTOR_ON_LEAVE,
  [ERROR_MESSAGES.KYC_ALREADY_SUBMITTED]: ERROR_CODES.KYC_ALREADY_SUBMITTED,
  [ERROR_MESSAGES.APPOINTMENT_NOT_FOUND]: ERROR_CODES.APPOINTMENT_NOT_FOUND,
  [ERROR_MESSAGES.APPOINTMENT_CONFLICT]: ERROR_CODES.APPOINTMENT_SLOT_UNAVAILABLE,
  [ERROR_MESSAGES.APPOINTMENT_PAST_DATE]: ERROR_CODES.APPOINTMENT_PAST_DATE,
  [ERROR_MESSAGES.APPOINTMENT_ALREADY_CANCELLED]: ERROR_CODES.APPOINTMENT_ALREADY_CANCELLED,
  [ERROR_MESSAGES.APPOINTMENT_ALREADY_COMPLETED]: ERROR_CODES.APPOINTMENT_ALREADY_COMPLETED,
  [ERROR_MESSAGES.INVALID_APPOINTMENT_STATUS]: ERROR_CODES.INVALID_APPOINTMENT_STATUS,
  [ERROR_MESSAGES.PRESCRIPTION_NOT_FOUND]: ERROR_CODES.PRESCRIPTION_NOT_FOUND,
  [ERROR_MESSAGES.PRESCRIPTION_ALREADY_SIGNED]: ERROR_CODES.PRESCRIPTION_ALREADY_SIGNED,
  [ERROR_MESSAGES.LAB_RESULT_NOT_FOUND]: ERROR_CODES.LAB_REPORT_NOT_FOUND,
  [ERROR_MESSAGES.LAB_REPORT_REQUEST_NOT_FOUND]: ERROR_CODES.LAB_REPORT_REQUEST_NOT_FOUND,
  [ERROR_MESSAGES.LAB_REPORT_ALREADY_REVIEWED]: ERROR_CODES.LAB_REPORT_ALREADY_REVIEWED,
  [ERROR_MESSAGES.DOCUMENT_NOT_FOUND]: ERROR_CODES.DOCUMENT_NOT_FOUND,
  [ERROR_MESSAGES.INVALID_FILE_TYPE]: ERROR_CODES.FILE_TYPE_NOT_SUPPORTED,
  [ERROR_MESSAGES.INVALID_IMAGE_TYPE]: ERROR_CODES.FILE_TYPE_NOT_SUPPORTED,
  [ERROR_MESSAGES.FILE_TOO_LARGE]: ERROR_CODES.FILE_TOO_LARGE,
  [ERROR_MESSAGES.FILE_REQUIRED]: ERROR_CODES.FILE_REQUIRED,
  [ERROR_MESSAGES.PAYMENT_NOT_FOUND]: ERROR_CODES.PAYMENT_NOT_FOUND,
  [ERROR_MESSAGES.PAYMENT_ALREADY_COMPLETED]: ERROR_CODES.PAYMENT_ALREADY_COMPLETED,
  [ERROR_MESSAGES.PAYMENT_SERVICE_UNAVAILABLE]: ERROR_CODES.PAYMENT_GATEWAY_UNAVAILABLE,
  [ERROR_MESSAGES.INSUFFICIENT_BALANCE]: ERROR_CODES.INSUFFICIENT_BALANCE,
  [ERROR_MESSAGES.PAYOUT_FAILED]: ERROR_CODES.PAYOUT_PROCESSING_FAILED,
  [ERROR_MESSAGES.INVALID_COUPON_CODE]: ERROR_CODES.INVALID_COUPON_CODE,
  [ERROR_MESSAGES.AI_CREDITS_INSUFFICIENT]: ERROR_CODES.AI_CREDITS_INSUFFICIENT,
  [ERROR_MESSAGES.AI_PROVIDER_UNAVAILABLE]: ERROR_CODES.AI_PROVIDER_UNAVAILABLE,
  [ERROR_MESSAGES.SPECIALTY_NOT_FOUND]: ERROR_CODES.SPECIALTY_NOT_FOUND,
  [ERROR_MESSAGES.SPECIALTY_ALREADY_EXISTS]: ERROR_CODES.SPECIALTY_ALREADY_EXISTS,
  [ERROR_MESSAGES.REFUND_NOT_FOUND]: ERROR_CODES.REFUND_NOT_FOUND,
  [ERROR_MESSAGES.TICKET_NOT_FOUND]: ERROR_CODES.TICKET_NOT_FOUND,
  [ERROR_MESSAGES.VALIDATION_ERROR]: ERROR_CODES.VALIDATION_ERROR,
  [ERROR_MESSAGES.BAD_REQUEST]: ERROR_CODES.BAD_REQUEST,
  [ERROR_MESSAGES.INTERNAL_SERVER_ERROR]: ERROR_CODES.INTERNAL_SERVER_ERROR,
  [ERROR_MESSAGES.SERVICE_UNAVAILABLE]: ERROR_CODES.SERVICE_UNAVAILABLE,
};
